# Generated by Django 5.0.6 on 2024-06-18 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="heroes/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IM", "Iron Man"),
                            ("CA", "Captain America"),
                            ("BM", "Batman"),
                            ("HK", "Hulk"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
