# Generated by Django 5.0.6 on 2024-06-18 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0002_herovariety_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryPopularIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "continent",
                    models.CharField(
                        choices=[
                            ("AS", "Asia"),
                            ("EU", "Europe"),
                            ("AF", "Africa"),
                            ("SA", "South America"),
                            ("NA", "North America"),
                            ("AT", "Antarctica"),
                            ("AU", "Australia"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "heroes_popular",
                    models.ManyToManyField(
                        related_name="countries", to="myApp.herovariety"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeroReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comment", models.TextField()),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="myApp.herovariety",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecialPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("power_strength", models.CharField(max_length=100)),
                (
                    "hero",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="superPower",
                        to="myApp.herovariety",
                    ),
                ),
            ],
        ),
    ]
